name: "Run Docs CI with UV"

on:
  pull_request:
    types: [opened, reopened, synchronize]
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'
  push:
    branches:
      - "study-baseline"
    paths:
      - 'docs/**'
      - 'mkdocs.yml'
      - '.github/workflows/docs.yml'

jobs:
  build-docs:
    uses: ./.github/workflows/docs.yml
    with:
      deploy: false
